### ISSUE TITLE
EXTREME Low FPS

### ISSUE THREAD

**Issue by Kamiling** [StrangeLoopGames/EcoIssues#11118]
Before the 8.0 update i had 40-60fps with setting at mid-high.

Now even with EVERYTHING at the lowest, my fps don't rise from 5.
Resolution, everything
![2](https://user-images.githubusercontent.com/23229044/52372717-a5847500-2a37-11e9-8408-9f302475f4aa.jpg)
![sin titulo](https://user-images.githubusercontent.com/23229044/52372718-a5847500-2a37-11e9-87de-6c727d8308a4.jpg)

**Comment by disfated** [comment]
Kinda related

FPS prior to 8.0
![2019-02-07 03 40 41](https://user-images.githubusercontent.com/430542/52378894-c2966380-2a8a-11e9-9fe1-c12e22cb3305.jpg)

FPS in 8.0 (same settings)
![2019-02-07 03 19 59](https://user-images.githubusercontent.com/430542/52378895-c2966380-2a8a-11e9-832c-61bc7df650de.jpg)

Integrated Intel HD Graphics 530
Not a gaming configuration but it was playable.

Btw:
![2019-02-07 03 51 48](https://user-images.githubusercontent.com/430542/52379288-e6a67480-2a8b-11e9-9ee4-3b72a327f776.jpg)

**Comment by metachronism** [comment]
@disfated
the baseline plant quality changed considerably between the two versions, where 100% quality is a lot more visible plants than prior, so its hard to compare past versions with this one, even with the same quality settings.  On some lower end devices such as intel hd graphics, you may want to try lowering that slider down.

**Comment by Kamiling** [comment]
Move the slider even lower? Out of the screen? haha

**Comment by SeanAtr0n** [comment]
could you send us your log file, might offer some clues, paste this into explorer to find it:

`%APPDATA%\..\LocalLow\Strange Loop Games\ECO`

**Comment by disfated** [comment]
Managed to gain slightly more fps by decreasing foliage quality to it's minimum (20%). Anyway, the overall picture is considerably worse compared to prior 8.0 with lower fps at the same time.

30 fps are available only in SuperMario mode :)

There were a couple of our guys also complaining about new graphics. Will try to get more information from them.

**Comment by jamesmclaren** [comment]
I have a brand new i7 machine with 32gb ram and a 1080 ti, and even with all the sliders on minimum, the frame rate is not great, and movement is slow and jerky, even when rotating on the spot. Interestingly, even on everything on max, the CPU,GPU and memory usage is fairly low. It seems to me there must be a lot of garbage collection going on in the background, or dynamic loading, that's how it feels when playing.

**Comment by Zaskersky** [comment]
Im also having problems with the new eco release,
system spec: ryzen 2600, rx 580, os:win10, 16gb ram,

Almost all setings max, when i start the game i get around 80-120fps at my solo base.
cpu runs at around 35%, and gpu at 100%.

But after like 2-5minits it varies my gpu usage goes down to around 70%, and a few minit later it some times drop to 20%. and my fps is around 10-40. with small freeze spikes.

I do have to say it saves a lot on the power bill from 225wat down to around 50wats but eco is unplayable ;)

Seems eco is not able to use the gpu/cpu fully any more in 0.8.0

**Comment by metachronism** [comment]
@Kamiling you should definitely not be seeing that low of fps.  Are you on a hybrid/dual GPU setup (such as a laptop) where the GPU only turns on occasionally?  We've seen issues in the past where Eco is not recognized as a game, and the laptop never uses the correct GPU, causing low framerates.  @jamesmclaren this sounds like it could be your issue as well, if you have a similar setup.

@disfated We don't regularly test on integrated GPUs so something could have definitely been made worse.  I'll try to repro on my old laptop and take a look.

@Zaskersky over time more of the world will load in, resulting in more things to draw and framerate getting lower.  It seems like as more of the world loads in, the more CPU bound you become, resulting in less GPU usage.

**Comment by Zaskersky** [comment]
@metachronism 
if the problem is as you say and and the game becomes more cpu bound as more of the world loads in, that still doesnt explain why the fps becomes super low and the gpu can no longer render what is on screen at normal speed, and if thats the case and it limited by the cpu why does it not use my cpu, cpu ussage doesnt increase over time it even decreases, as eco is no longer ussage the gpu to the max it also usses less cpu, cpu for eco is between 20-30%

**Comment by metachronism** [comment]
@Zaskersky well it does use your CPU, or at least all of one core.  Unity doesn't yet make optimum use of all CPUs for rendering.  If you have a 4C/8T machine, utilizing all of one core will only show 12.5% CPU usage.

For Eco specifically, if you have a higher-end or desktop GPU you'll tend to be CPU bound, where the only thing that will really impact frame rate significantly will be view distance (less work for the CPU to tell the GPU what to draw);

**Comment by jamesmclaren** [comment]
my machine is a high end desktop spec

Processor (CPU) | Intel® Core™ i7 Six Core Processor i7-8086k (4.0GHz) 12MB Cache
Motherboard | Gigabyte Z370 AORUS Gaming 7: ATX, LG1151, USB 3.1, SATA 6GBs - RGB Ready
Memory (RAM) | 32GB Corsair VENGEANCE DDR4 3200MHz (4 x 8GB)
Graphics Card | 11GB NVIDIA GEFORCE GTX 1080 Ti - HDMI, 3x DP GeForce - GTX VR Ready!
1st Storage Drive | 1TB Samsung 860 EVO 2.5" SSD, SATA 6Gb/s (upto 550MB/sR \| 520MB/sW)
2nd Storage Drive | 8TB SEAGATE BARRACUDA PRO 3.5", 7200 RPM 256MB CACHEChange to: 6TB SEAGATE BARRACUDA PRO 3.5", 7200 RPM 256MB CACHE
Processor Cooling | CoolerMaster MasterLiquid Lite 120 High Performance Liquid Cooler
Sound Card | Creative Sound Blaster Z 5.1 PCI-E Soundcard - OEM

it has 6 cores and 12 logical processors.
cpu stays around 10%, gpu around 30% on default settings, and about 25fps, my main problem is even when rotating it stutters and jerks. I can put all the settings on minimum, and the fps increases to around 60, but the stuttering remains

**Comment by disfated** [comment]
Posting this just to let you guys know.

I've been around 0.8.0 for quite some time on different servers and I can be sure now that performance issues are widespread and systematic.
Unfortunatelly, most of people tend to silently adjust to their poor experience or even quit the game entirely.

I heard a lot of people complaining that their experience became significantly worse compared to what they had before v0.8.

There is a bunch of folks that have extremely expensive GPUs, however they are forced to considerably lower graphic settings to get at least minimum playable fps.

Finally, couple of folks (including me) had to quit Eco until it is playable again.

I know that you have a myriad of other severe bugs to fix now, but in the end I hope you find time to look deeper into this one...

**Comment by johnkslg** [comment]
Thanks for the detailed report @disfated and all, we're focused on this for our next release.

**Comment by DjSapsan** [comment]
GTX 1060 6 gb. Before last updates i had huge FPS impact over time or after some traveling or in the forests: 5-25 FPS. Preferences from lowest to medium doesnt make difference. Today its a little better. But still i see FPS drops over time and when traveling. Preferences up to hight global illumination is 72 but going down over time. In process of the game in need gradually make lower preferences.

**Comment by mirasrael** [comment]
Hi @DjSapsan 
In incoming 8.2 we hand another set of optimizations, also some which should affect degrading performance after long traveling. So please keep us updated after 8.2 release.
Thanks!

**Comment by ViewableGravy** [comment]
I have also been having this issue. 
for reference I have a Ryzen 7 2600, an RTX 2080 and 16gb of ram,
I am currently on build 0.8.2.9. When i open my game i get about 70-80 fps if uncapped but after playing for an hour or two I notice that I am getting more like 25 fps. As stated by others, this issue is fixed simply by restarting the game.
Nothing on my pc is throttling and my ram is normal.
I think the most fundamentally important thing at the moment should be performance personally since the target audience of this game is likely unable to even run it with half the settings on. 

Just thought I would post to indicate that this issue is still happening.

**Comment by redwyre** [comment]
The coming 8.3 (in a week or two) adds another set of performance fixes, if you want to give it a go before release the details are on discord.

**Comment by clairmont32** [comment]
Hi, I'm having the same issue as previously reported. I'm stuck at 15 FPS after traveling about half of the world and lowering settings hasnt helped at all. Version is 0.8.3.3 beta, Feb 6 2020.

**Comment by VekSan24** [comment]
Hi there, 
I have the same issues, i'm not sure if my pc is too bad, but i have no problems with others games (on low/medium) 
my game run arround 12/13 FPS afters few minutes of playing. 
I saw the message before but it was in 2019, so i'm pretty sure you made changes. 

But i'm still having issues. 

Sorry english isn't my native language.

**Comment by clairmont32** [comment]
@VekSan24 what're you system specs? Does it get better if you set the target frame rate to 30 or 60?

**Comment by Marcvader3** [comment]
I had a similiar Problem but i was able to fix it.
I turned on Volumetric Fog and my fps went from 10 to 80.

**Comment by ZockerBoysHD** [comment]
i can indeed report similar EXTREM Low FPs issues
Running the following system:

Ryzen Threadripepr 1920x 12C 24T at 4,5GHz
32GB DDR4 Ram
1070 TI 8GB

Playing on a Private Server, 4K Monitor, Game res. set to 1080p

EVERYTHING on its Lowest resulting in ONLY!! 40-50ish FPS.
Everything to its Highest giving similar results. No matter if VSync is enabled or not. (normally gives me more fps in any game)
