### ISSUE TITLE
USER ISSUE: Cannot connect to servers

### ISSUE THREAD

**Issue by SystemSlayer525** [StrangeLoopGames/EcoIssues#12418]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
Try to connect to a server

**Expected behavior:**
connect to a server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Server encountered an exception:

<size=60.00%>Exception: WebException
Message:The remote server returned an error: (500) Internal Server Error.
Source:System

System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)</size>
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Server encountered an exception:

<size=60.00%>Exception: WebException
Message:The remote server returned an error: (500) Internal Server Error.
Source:System

System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)</size>
```

**Comment by D3nnis3n** [comment]
We lately had someone else contacting us having this issue. I still have no idea why this actually happens. People with that issue can play fine via Steam and on servers that don't require authentication, but they cannot login to the game via SLG client or play on normal servers.

It seems likely that there either is an issue with their accounts, the authserver itself or something on their computers blocking access to the the authserver. Given the "RequireAuthentication" option is removed in 8.2 they are barred for playing, which makes this high priority and if 8.2 ships before this is fixed an actual critical issue in a release build.

@mirasrael @rainfarmer Would be good if you could take a look.

**Comment by mirasrael** [comment]
This is issue was reported 20 days ago. Does user still have this issue? Looks like it was temporary error with auth server. Due to error code (500) it was because some error reported from auth server rather than auth server inaccessibility.

**Comment by D3nnis3n** [comment]
I don't know for this user, but for the user on support i care about - he is having this issue since 8.1 and cannot play at all at no given time.

**Comment by D3nnis3n** [comment]
![500](https://user-images.githubusercontent.com/25908592/59594873-fcd8d700-90f4-11e9-97f0-7bdd2bb73f35.png)

**Comment by mirasrael** [comment]
Fixed in database.
