### ISSUE TITLE
[0.9.0 staging-1314] Server Crash with Work Party

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14267]
Step to reproduce:
- create Work Party with reputation payment:
![image](https://user-images.githubusercontent.com/45708377/71541925-f3b4a680-2970-11ea-83d9-5cd100b2a9e0.png)
- add some ingredients or labor by yourself:
![image](https://user-images.githubusercontent.com/45708377/71541952-3d04f600-2971-11ea-880e-b35b5a3ffaa0.png)
- complete or delete work party.
- Server crash because you can't give reputation yourself:

```
--BEGIN DUMP--
Dump Time
12/28/2019 12:55:09

Exception
Exception: InvalidOperationException
Message:Cannot give rep to yourself.
Source:Eco.Gameplay

System.InvalidOperationException: Cannot give rep to yourself.
   at Eco.Gameplay.Economy.ReputationManager.GiveRep(String sourceUser, String targetUser, Single val, String note)
   at Eco.Gameplay.Economy.WorkParties.ReputationPayment.PayUser(Laborer laborer, Single amount)
   at Eco.Gameplay.Economy.WorkParties.ReputationPayment.<WorkFinished>b__2_1(Laborer x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at Eco.Shared.Utils.StringExtensions.TextList(IEnumerable`1 e, String sep)
   at Eco.Gameplay.Economy.WorkParties.ReputationPayment.WorkFinished()
   at Eco.Gameplay.Economy.WorkParties.WorkParty.<>c.<OnWorkFinished>b__30_0(Payment x)
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at Eco.Shared.Utils.StringExtensions.TextList(IEnumerable`1 e, String sep)
   at Eco.Gameplay.Economy.WorkParties.WorkParty.OnWorkFinished()
   at Eco.Gameplay.Economy.WorkParties.WorkParty.Cancel(Player player)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

--END DUMP--
```

**Comment by johnkslg** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/3536496/71631919-65366400-2bc0-11ea-9601-9fca0159ad25.png)

**Comment by beastyn** [comment]
Got clent crash when was trying to check this obe.
Crash after adding a labor (party like in this example)
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.WorkParties.ReputationPayment.WorkFinished()
   at Eco.Gameplay.Economy.WorkParties.WorkParty.<>c.<OnWorkFinished>b__31_0(Payment x)
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at Eco.Shared.Utils.StringExtensions.TextList(IEnumerable`1 e, String sep)
   at Eco.Gameplay.Economy.WorkParties.WorkParty.OnWorkFinished()
   at Eco.Gameplay.Economy.WorkParties.WorkParty.OnWorkPerformed(User user, Work work, Single percentDelta, String message)
   at Eco.Gameplay.Economy.WorkParties.LaborWork.UpdateWorkDone(User user, Single quantity)
   at Eco.Gameplay.Economy.WorkParties.LaborWork.ActionPerformed(GameAction action)
   at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
   at Eco.Gameplay.Economy.WorkParties.WorkParty.ActionPerformed(GameAction action)
   at Eco.Gameplay.Economy.WorkParties.WorkPartyManager.<>c__DisplayClass6_0.<ActionPerformed>b__1(WorkParty x)
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.GameActions.ActionUtil.ActionPerformed(GameAction action)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, IEnumerable`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
   at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameActionPack pack, Boolean notify)
   at Eco.Gameplay.Items.WorkOrder.TryToContributeLabor(Player player, Single contributionMultiplier)</size>
```

**Comment by beastyn** [comment]
And server crash was there too after deleting this party
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.WorkParties.ReputationPayment.WorkFinished()
   at Eco.Gameplay.Economy.WorkParties.WorkParty.<>c.<OnWorkFinished>b__31_0(Payment x)
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at Eco.Shared.Utils.StringExtensions.TextList(IEnumerable`1 e, String sep)
   at Eco.Gameplay.Economy.WorkParties.WorkParty.OnWorkFinished()
   at Eco.Gameplay.Economy.WorkParties.WorkParty.Cancel(Player player)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by johnkslg** [comment]
This is working in my local tests, maybe the fixes didn't make it into the staging build somehow? Can you test again in next staging.

**Comment by beastyn** [comment]
Don't have server crash, but still have the client crash. Will make separate issue for this one.
