### ISSUE TITLE
[0.9.0 stagong-1542] Small Line Spacing

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16176]
![image](https://user-images.githubusercontent.com/45708377/81271292-96cea880-9054-11ea-92cf-c8872122671e.png)
![image](https://user-images.githubusercontent.com/45708377/81271340-a1893d80-9054-11ea-9477-c36fc9829964.png)
![image](https://user-images.githubusercontent.com/45708377/81271440-c1206600-9054-11ea-9191-c020ef9e835e.png)

**Comment by SlayksWood** [comment]
> Overlaps. Text needs to be adjusted in size.
> 
> ![iconbig](https://user-images.githubusercontent.com/25908592/81324519-61977a00-9097-11ea-8cbb-e1dcb789bc40.png)

**Comment by serpopov** [comment]
first one will be fixed with refactoring

**Comment by SlayksWood** [comment]
Seems still could be a little overlap:
![image](https://user-images.githubusercontent.com/45708377/82289168-db3f3a00-99ac-11ea-8027-9ec8cfcfe2a9.png)
![image](https://user-images.githubusercontent.com/45708377/82289254-0de93280-99ad-11ea-84f9-85837d4652be.png)
Fixed in chat:
![image](https://user-images.githubusercontent.com/45708377/82289317-2eb18800-99ad-11ea-870e-576d4e930d82.png)

**Comment by SlayksWood** [comment]
Still an issue in module tab:
![image](https://user-images.githubusercontent.com/45708377/85252222-feee1800-b463-11ea-9a50-3443790846f6.png)

**Comment by beastyn** [comment]
Still not enough space in the modules
![bandicam 2020-06-24 14-34-41-150](https://user-images.githubusercontent.com/27898520/85531133-ee869a80-b627-11ea-8195-c3008e791bf2.jpg)
