### ISSUE TITLE
[0.9.0 staging-1686] Vehicles lost max weight in UI

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17332]
![image](https://user-images.githubusercontent.com/45708377/88626888-113b2180-d0b4-11ea-8232-2e1f431bbcbc.png)

**Comment by SlayksWood** [comment]
fixed in last staging
![image](https://user-images.githubusercontent.com/45708377/88780699-0eaff900-d194-11ea-9d90-822f057b3287.png)

**Comment by SlayksWood** [comment]
it happens again:
![image](https://user-images.githubusercontent.com/45708377/89757510-23728200-daee-11ea-8da6-08e13b85f830.png)

**Comment by SlayksWood** [comment]
> Also note the weight limit is there when the world first starts then disappears randomly later.

**Comment by Draveynz** [comment]
![cartweight](https://user-images.githubusercontent.com/68322457/90219257-3e354700-ddcb-11ea-912e-7d9dee0f4afd.png)
still happening
