### ISSUE TITLE
Icons on signs display acts weirdly depending on distance

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#17527]
![image](https://user-images.githubusercontent.com/25908592/89296951-6a322900-d663-11ea-9dad-cef322316f5b.png)

If you move towards, the icon will roll down, being fully displayed, if you move backwards more and more will roll up and be invisible.

**Comment by D3nnis3n** [comment]
You can also jump in front of it, then it goes way up and down when you fall again :D

**Comment by redwyre** [comment]
Do you mean just part of it becomes invisible? The icon itself doesn't move?

**Comment by D3nnis3n** [comment]
Sorry, yes thats what i meant.

**Comment by D3nnis3n** [comment]
![shader](https://user-images.githubusercontent.com/25908592/89395159-3e6b7d80-d70d-11ea-93f5-776eb6e8503d.png)

When flying that stuff moves up into the air. Seems like shader affected or something? Hasn't been the case in 8.3.

**Comment by MazonDel** [comment]
This issue was fixed with the merging of: https://github.com/StrangeLoopGames/Eco/pull/6805

**Comment by IcedForge** [comment]
It should fade with the sign i would assume?
Right now it is always there, as long as its in a loaded chunk the player will see the sign regardless of distance / graphic settings.
![Screenshot_100.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/4794e2c9-18cb-4828-acc3-533b494aa1ab)

vs the draw distance of the sign itself.
![Screenshot_101.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/54ff7678-4407-43dd-984f-5e971c046168)

**Comment by serpopov** [comment]
extra: after change text of sign it flyes upward again

**Comment by SlayksWood** [comment]
Still an issue:
>It should fade with the sign i would assume?
> Right now it is always there, as long as its in a loaded chunk the player will see the sign regardless of distance / graphic settings.

![image](https://user-images.githubusercontent.com/45708377/99070028-89284b80-25c0-11eb-9326-2e7ff8ebd0be.png)

**Comment by serpopov** [comment]
Could you test it with two people, when one is changing sign text while other watching this realtime.
Also start game at distance and then get closer to sign to let sign text to load realtime.
