### ISSUE TITLE
USER ISSUE: traps not recognizing fresh water

### ISSUE THREAD

**Issue by Spaceferret42** [StrangeLoopGames/EcoIssues#18035]
\
**Version:** 0.9.0.0 beta staging-1749

**Steps to Reproduce:**
1. place trap in river or stream
2.harvest once and or pick up once

**Expected behavior:**
continue to work in same location with fresh water condition met

**Actual behavior:**
will no longer recognize fresh water no mater where you move it to

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Fresh water was fixed in nearby versions, I don't have problem with fish trap now:
![image](https://user-images.githubusercontent.com/45708377/92105960-51489f00-edec-11ea-864a-8df6d7296f42.png)
Can you provide screenshot with fresh water layer:
![image](https://user-images.githubusercontent.com/45708377/92106102-8bb23c00-edec-11ea-8664-a49db19b4b70.png)
And if you don't have any fresh water then provide save file. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by Spaceferret42** [comment]
The bug actually managed to fix it self after letting the trap stay in its location about 10 minutes as if it took it awhile to realize it was in fresh water

**Comment by mirasrael** [comment]
Guess it start working when world simulation tick happened (it takes about 10 minutes). If old world it has invalid data on startup, but then fixed with next world tick.

**Comment by Spaceferret42** [comment]
It is saying all is well but still has a red dot and no longer catching fish
![20200903140538_1](https://user-images.githubusercontent.com/35748070/92156942-4fcca600-edef-11ea-80e1-1e32ff942143.jpg)
![20200903140634_1](https://user-images.githubusercontent.com/35748070/92156943-51966980-edef-11ea-963e-4beca62bad0c.jpg)
![20200903140638_1](https://user-images.githubusercontent.com/35748070/92156947-52c79680-edef-11ea-9652-008b764ea4b7.jpg)
also it is a server not a private hosted game on my pc

**Comment by beastyn** [comment]
@Spaceferret42 do you have such issue with fresh world after 9.0.1 update?

**Comment by Spaceferret42** [comment]
Havn't tried yet figured I would hold off on fishing since the server I played on reset until ocean fishing is in

Sent from Yahoo Mail on Android 
 
  On Thu, Sep 10, 2020 at 4:56 AM, Anna<notifications@github.com> wrote:   


@Spaceferret42 do you have such issue with fresh world after 9.0.1 update?

**Comment by beastyn** [comment]
So issue is still here #18197 but seems to be related to the position under bridges. Should be fixed with #18291
