### ISSUE TITLE
Elections possibly broke once the new update was added.  I just took this screenshot.

### ISSUE THREAD

**Issue by sirPattrick** [StrangeLoopGames/EcoIssues#20311]
![image](https://user-images.githubusercontent.com/36024353/106554433-fc1ad180-64e0-11eb-83e9-d31481de17ac.png)
The game still considers the election to be going on.  But the Elecetion laws as far as I can tell state the Max time should be 24 hours.

**Comment by sirPattrick** [comment]
as you can see in the picture, at the time of the screenshot, it was at 25.25 hours.

**Comment by sirPattrick** [comment]
I fixed it by recasting my vote.

**Comment by sirPattrick** [comment]
Someone just complained about this in discord today.  Is this what happens when the server updates during an election, or is this an actual bigger issue?

**Comment by Dave247** [comment]
This has been happening constantly on the server I'm currently playing on and I'm not entirely sure what might have caused it. The very first time when we wrote our constitution and passed it without issue so we then started adding some laws though I can't remember if any of them passed, as the next day we were expanding the capitol building which caused the 20 minutes countdown timer to start and unfortunately wasn't finished which invalidated it and we had to ratify it again.

Ever since then most if not all of the elections seem to bug out and not end at the end of the 24 hour period when they are supposed to.

**Comment by Dave247** [comment]
Also another thing that is likely related to this. When a the election time remaining is in the negative and having someone recast their vote to end it, the notifications that appear will say that the election failed, even though it actually passed. Thankfully there doesn't seem to be any other side effects past that as the changes will still show up in the government windows and all act as they should.

**Comment by Dave247** [comment]
It might be useful to this issue but I have uploaded the server's save file where we had this happen to us here https://github.com/StrangeLoopGames/EcoIssues/issues/20864#issuecomment-798869641

**Comment by TwixterZ** [comment]
@Dave247 these issues are parts of a bigger issue that is being looked into for 9.3 update as part of rework in civics object handling

**Comment by Dave247** [comment]
Can report the issue is sadly still present in 0.9.3.1 beta release-204

**Comment by IronyTroll** [comment]
We are still experiencing an ongoing issue where elections do not end unless the server has been rebooted. If the election were to run for 24hrs, it has been up to 100 hours before it 'completed' when the server got rebooted.

Below is a list of possibly related tickets.

#20565
#22200
#22201
#20311

**Comment by D3nnis3n** [comment]
Merged with #22201
