### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21526]
![image](https://user-images.githubusercontent.com/25908592/115808077-12eb0900-a3ea-11eb-81ae-926411ccfe43.png)
[Player (3).log](https://github.com/StrangeLoopGames/EcoIssues/files/6362206/Player.3.log)
[crash (2).log](https://github.com/StrangeLoopGames/EcoIssues/files/6362209/crash.2.log)

**Comment by gzatravkin** [comment]
[error (1).log](https://github.com/StrangeLoopGames/EcoIssues/files/6362831/error.1.log) - here goes crash error.
 Can't reproduce, any help? @IcedForge

**Comment by SlayksWood** [comment]
@D3nnis3n Need PC specification and game version, it looks like our sudden 9.3.2 release. Also his log file just open and close game without trying to connect

**Comment by D3nnis3n** [comment]
It crashes at game start, hence there is no connection try. I have notified the user about this issue and hope he'll be able to provide the PC specs and version, though he shouldnt have 9.3.2 anymore as we had contact over a full day distributed.

**Comment by B3lf4** [comment]
Please find attached the full system specs taken from the system information application
[system specs.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6363086/system.specs.txt)

Given that the games crashes on the loading screen, I am not able to say which version is installed. I tried to find a game version in the game files or Steam properties with no luck. I can only say that the game has been updated on April 20th at 4:45pm PST, it's up to you to understand which version was current at that time.

**Comment by Daniel-Magulado** [comment]
Hi @B3lf4, just to add to our investigation to narrow possible causes, do you have your RTX 2070 overclocked?

**Comment by IcedForge** [comment]
Please make sure to update your drivers and that there is no anti virus running interference as from the looks of it you have 3 different versions of the same AV installed 
c:\program files (x86)\kaspersky lab\kaspersky security cloud 21.1\avp.exe
c:\program files (x86)\kaspersky lab\kaspersky security cloud 21.2\avp.exe
c:\program files (x86)\kaspersky lab\kaspersky security cloud 21.3\avp.exe
Each with its own nested possibilities of interfering with non associated systems.

Your graphics drivers seems to be from december which i recall we have had a lot of issues with that were resolved in jan/feb so i would recommend make sure to upgrade those using clean installation.

**Comment by B3lf4** [comment]
I have just updated the the video drivers to the latest stable release from nVidia (466.11) with a clean install.
I also paused Kaspersky AV software before trying again to launch ECO but i have still the same result: the game doesn't start
Please find attached the new player logs as well as the crash logs

[Crashes.zip](https://github.com/StrangeLoopGames/EcoIssues/files/6367089/Crashes.zip)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6367067/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6367068/Player-prev.log)

**Comment by IcedForge** [comment]
Do you have any crash dumps / callstacks at 
C:/Users/b3lfa/AppData/Local/Temp/Strange Loop Games/Eco/Crashes then please upload them as well

**Comment by B3lf4** [comment]
I already uploaded them: they are in the crash.zip folder. Github didn't allowed me to attach the .dmp files to the message

**Comment by B3lf4** [comment]
I was able to capture the strange "error" window I can see briefly just before the game crashes. maybe it's useful, but I assume the crash log is more meaningful
![eco error msg](https://user-images.githubusercontent.com/83056672/116012160-bbad8a00-a5dd-11eb-84f1-6c0151750b94.jpg)

**Comment by B3lf4** [comment]
Ok, it seems that there is no movement here...
too bad. I'll ask for a refund before the 2 weeks window closes with Steam.
Best of luck for future development!

**Comment by IcedForge** [comment]
Unfortunately we will need to raise this issue with unity as there is no easy fix for this it seems.

**Comment by WeaselDog** [comment]
Sorry we could not resolve your issue in time. Thank you for your report.
