### ISSUE TITLE
crash performing trade at store

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#2376]
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC PerformTrade on StoreComponent!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Components.StoreComponent.PerformTrade(Player purchaser, BSONObject tradeData)

Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by MarjieAVolk** [comment]
Man do I wish for a line number right now

**Comment by Fank** [comment]
Maybe related to #2253

**Comment by MarjieAVolk** [comment]
Don't think so

**Comment by johnkslg** [comment]
Tested stores extensively, couldn't find any problems. I think this was fixed by other changes most likely.

**Comment by stromhurst** [comment]
Happend the similar with me today in alpha 6.1.1 release. I was selling about 459 Huckleberry and 620 wheat at the same time, Shop was using the serverwide minted currency we have, not the players credit. Maybe the player was out of the server wide currency? but definately it is not fixed so please open it again.

`Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC PerformTrade on StoreComponent!

Value cannot be null.
Parameter name: key


Stack:
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at Eco.Gameplay.Items.InventoryChangeSet.MoveItemsInternal[TKey](Type itemType, Int32 quantity, Inventory source, Inventory destination, Func`2 sourceStackPredicate, Func`2 sourceStackOrder)
   at Eco.Gameplay.Components.StoreComponent.PerformTrade(Player purchaser, BSONObject tradeData)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)
`
