### ISSUE TITLE
Picking Up and Replacing Mint Unlinks Currency

### ISSUE THREAD

**Issue by ECO-ExPLiCiT** [StrangeLoopGames/EcoIssues#3140]
I have now lost the means to mint any new global currency on my server because I had to pick up and replace the mint because it would not recognize the ingots in my inventory until I did. 

There should be an option for the the person placing the mint to link it to and previously created currency by that person.

Also I believe there should be some way you can take any coin that has been minted and melt 10 of them back into an ingot.

**Comment by Dr-Hardware** [comment]
can move mine around no drama, are you placing it on claimed ground?  was it placed on claimed ground initially
?

**Comment by MarjieAVolk** [comment]
Picking up a mint and placing it again should save the currency that was on it.  Did you have another mint in your inventory that you stacked with this mint?  That is a known problem that can cause the mint to lose its information (see https://github.com/StrangeLoopGames/EcoIssues/issues/2928).

Also, the problem with the # of ingots in your inventory not updating should be fixed soon if it isn't already in staging >> Just got back from the holidays so I'm behind on release status lol.

**Comment by MarjieAVolk** [comment]
I went and looked at this, and I believe picking it up and placing it works, it's just if you stack it with another mint that weird things happen.  So closing as duplicate of #2928

**Comment by Sonic1305** [comment]
This problem is still present! I had to remove the Mint, put it back in a chest and after a few hours tried to place it again and I lost the ability to create my currency and have to create a new one. You should also remove the ability to create 2 Currencies with the same name.

**Comment by MarjieAVolk** [comment]
You are sure you didn't stack the mint with another mint?
