### ISSUE TITLE
Resizeable UIs jump around screen when being resized. 

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#6344]

**Comment by MarjieAVolk** [comment]
Fixed

**Comment by MarjieAVolk** [comment]
:'( I don't know whyyyy

**Comment by MarjieAVolk** [comment]
unityyyyy

**Comment by MarjieAVolk** [comment]
I have been trying to send a bug report to Unity about this, apparently sending them a bug report takes 8 hours, who knew

![image](https://user-images.githubusercontent.com/23460210/38064226-c68bcb00-32b1-11e8-8667-260c571b73d0.png)

**Comment by raykai** [comment]
ya i have the same prob when resizing the minimap it then jumps on the left top of the screen then i need to drag it to the top right of the screen but if i resize it ... it goes back to the top left of the screen. this bug is still present in Beta 7.3.1 and 7.3.0

**Comment by MarjieAVolk** [comment]
Okay, well I tested this out on unity 2018, and this did not happen on 2018.  So we have to update to 2018.

**Comment by MarjieAVolk** [comment]
We will update to 2018 in the next major version, so I'm going to close this as "handled"
