### ISSUE TITLE
Crash after placing asphalt ramp

### ISSUE THREAD

**Issue by WizyTheNinja** [StrangeLoopGames/EcoIssues#8214]
Was creating a new road system, managed to place a few asphalt ramps, but one time that I placed it, My client crashed instantly and now whenever I try to rejoin the server, I crash after loading world is finished.
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/2144450/error.log)

Version: 0.7.5.0 beta

Steps to Reproduce:
Place asphalt ramp

Expected behavior:
Continue placing asphalt ramps

Actual behavior:
Crash to desktop continously
Will confirm if its just for me, or if for everyone on server later.

EDIT:
Confirmed cause of crash is from placing item inside of player.
Jumping and placing the item, or falling into where you place it are good ways to produce the bug.

**Comment by BurningEnlightenment** [comment]
can also happen if you somehow glitch into existing blocks, happened to me while picking up a cart standing on a ramp in a tunnel.
@WizyTheNinja if someone else removes the blocks you are stuck in, you should be able to continue playing.

**Comment by WizyTheNinja** [comment]
@BurningEnlightenment Yes that is what I ended up doing. Once the server owner was online and able to play, I had him remove the ramp and was able to connect instantly. This can be bad for solo players ,or people playing during different time zones than the other players on the server. Should be fixed immediately as there is no way to fix it without outside help.

**Comment by BurningEnlightenment** [comment]
the crash is still reproducible with the 0.7.5.1-beta release
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/2150147/error.log) [crash.dmp.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2150150/crash.zip)

**Comment by SeanAtr0n** [comment]
fixed in 7.5.1 client hotfix
