### ISSUE TITLE
Small Wood Cart does’nt “see” any Stockpile

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#9293]
Version: v0.7.7.1-beta
Drag the cart to another place intending to unload it – open it – astonishment – no stockpile
(happened multiple times)
![strorage 2](https://user-images.githubusercontent.com/38510829/45268073-ec197780-b477-11e8-9fe0-fb22463e6be2.jpg)

after game restart
![strorage restart](https://user-images.githubusercontent.com/38510829/45268084-05babf00-b478-11e8-9b92-9c0df0df91af.jpg)

**Comment by MarjieAVolk** [comment]
I wasn't able to reproduce this over here.  But I've also had people complain that linked inventories don't disappear from carts after moving the cart away.

So, I notice that your first screenshot is missing the 'none' message that would normally be there
![image](https://user-images.githubusercontent.com/23460210/45329711-91832880-b516-11e8-9a94-2f2df09a95d9.png)

This makes me think there were exceptions getting thrown.  Could you attach your output_log.txt file?

**Comment by Nicolausi113** [comment]
Can’t find an output_log file in game-dir nor in appdata, but found a NullRefExeption in server/dump, but not necessarily caused on this problem?!
The issue seems very random and till now I have no systematic way to reproduce, maybe I find one.
And yes, I also noticed one time inventories that couldn't exist in the near.

The NullRefExeption:
[ServerCrash NullReferenceException 09082923.ecodmp.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2369953/ServerCrash.NullReferenceException.09082923.ecodmp.txt)

**Comment by elfl0rd** [comment]
win+r - %appdata%\..\LocalLow\Strange Loop Games\Eco\

**Comment by MarjieAVolk** [comment]
Thanks!  Sorry I didn't give better instructions for finding the file.  You are right that the server crash is unrelated.  It looks like that crash was an error while shutting down the server.  Which is odd, but I suppose not the worst thing that can happen.

I did find this in your output log, which might be relevant:
```
Exception in view notify: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException
  at (wrapper managed-to-native) UnityEngine.MonoBehaviour.StopAllCoroutines(UnityEngine.MonoBehaviour)
  at UI.StorageUI.UpdateLinked () [0x00000] in <49fbd59aadd44fe7aa12521c19d3a233>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <f826c2584fc94ec19a48a6576640bdc5>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <f826c2584fc94ec19a48a6576640bdc5>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <f826c2584fc94ec19a48a6576640bdc5>:0 
  at Eco.Shared.View.Subscriber.Invoke () [0x00016] in <87ad411c44194e6696a91acb8cbb3d86>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x0007e] in <87ad411c44194e6696a91acb8cbb3d86>:0 
```

**Comment by MarjieAVolk** [comment]
I investigated this exception a bit, but I am not sure that it is actually relevant, and I haven't found anything yet.

The next time you see this problem (either missing inventories or incorrectly present inventories), if you could attach your output_log.txt file again right afterwards, I can double check that this exception is actually related.

**Comment by Nicolausi113** [comment]
This problem did not appear again since I opened that issue. I’ve updated to v7.7.2 a day later and maybe this is the reason and is fixed now in some way. So I think this ticket can be closed – thanks for care about.

**Comment by Nicolausi113** [comment]
Version: v0.7.7.2-beta

Against my expectation happened this issue now 3 times at the same position and same situation, it was nearly reproducible.
I copied the output_log file during running game and attached it here, but there are pretty much exceptions as I saw, not an easy work.
I copied also the server backup for this time period and will keep it for a while in case there were interest to examine it. I can describe the positions A and B where I drove the cart from and to. The file size is 134 MB. Feel free to ask me back if interested, I then have to attach some more information about the way points.

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2431782/output_log.txt)

Missing inventories
![l2 only clip](https://user-images.githubusercontent.com/38510829/46260417-d67ef700-c4e5-11e8-99c4-455f7c99633b.jpg)

After restart
![l1-l3 clip](https://user-images.githubusercontent.com/38510829/46260425-fe6e5a80-c4e5-11e8-9e6a-161886cf2d8f.jpg)

**Comment by D3nnis3n** [comment]
Probably also related to https://github.com/StrangeLoopGames/EcoIssues/issues/9289

**Comment by Splutty** [comment]
In 8.0 this (or a variation of this) is still happening, where I'll load my cart with tailings near my blast furnace, then drive it all the way to the elevator, go down the elevator, and then when opening the cart it will show the storage list like it was when I loaded the tailings, instead of the new storages that are now near me where I wish to unload the tailings.

This seems to be somewhat random, but it feels like the cart maintains a 'cached' copy of what storages are near it at a certain point in time. (Which sometimes is no storage at all).

The fact the output log doesn't contain timestamps doesn't help..

**Comment by feildmaster** [comment]
It's caused by client desyncing, and allows one to effectively teleport resources around the world because the client believes the cart is still in one location, while the location you're at knows (server side) that the cart is near it.

It leads me to believe you can make a potential hack to move items anywhere without knowing more than 2 destination locations

**Comment by SlayksWood** [comment]
Seems fixed.
